
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Download, Share2 } from 'lucide-react';

interface ShareableReportProps {
  keyword: string;
  score: number;
  lastUpdated: string;
  results: any[];
}

export function ShareableReport({ keyword, score, lastUpdated, results }: ShareableReportProps) {
  const handlePrint = () => {
    window.print();
  };

  const getScoreColor = (score: number) => {
    if (score >= 80) return 'text-green-600';
    if (score >= 60) return 'text-yellow-600';
    return 'text-red-600';
  };

  const getSentimentColor = (sentiment: string) => {
    switch (sentiment) {
      case 'POSITIVE': return 'bg-green-100 text-green-800';
      case 'NEGATIVE': return 'bg-red-100 text-red-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  return (
    <div className="max-w-4xl mx-auto p-8 bg-white">
      {/* Print Button - Hidden in print */}
      <div className="mb-6 print:hidden">
        <Button onClick={handlePrint} className="flex items-center gap-2">
          <Download size={16} />
          Download PDF
        </Button>
      </div>

      {/* Header */}
      <div className="text-center mb-8">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">
          Reputation Report
        </h1>
        <p className="text-lg text-gray-600">
          Keyword: <span className="font-semibold">{keyword}</span>
        </p>
        <p className="text-sm text-gray-500">
          Generated on {lastUpdated}
        </p>
      </div>

      {/* Score Summary */}
      <Card className="mb-8">
        <CardHeader>
          <CardTitle>Reputation Score</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex items-center justify-center">
            <div className="text-center">
              <div className={`text-6xl font-bold ${getScoreColor(score)}`}>
                {score}
              </div>
              <div className="text-xl text-gray-600 mt-2">
                out of 100
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Results Table */}
      <Card>
        <CardHeader>
          <CardTitle>Search Results Analysis</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="overflow-x-auto">
            <table className="w-full border-collapse">
              <thead>
                <tr className="border-b">
                  <th className="text-left p-3 font-semibold">Rank</th>
                  <th className="text-left p-3 font-semibold">Title</th>
                  <th className="text-left p-3 font-semibold">Domain</th>
                  <th className="text-left p-3 font-semibold">Sentiment</th>
                  <th className="text-left p-3 font-semibold">Control</th>
                </tr>
              </thead>
              <tbody>
                {results.map((result) => (
                  <tr key={result.id} className="border-b">
                    <td className="p-3 font-medium">#{result.rank}</td>
                    <td className="p-3 max-w-xs">
                      <div className="truncate" title={result.title}>
                        {result.title}
                      </div>
                    </td>
                    <td className="p-3 text-sm text-gray-600">
                      {result.domain}
                    </td>
                    <td className="p-3">
                      <Badge 
                        variant="secondary" 
                        className={getSentimentColor(result.sentiment)}
                      >
                        {result.sentiment}
                      </Badge>
                    </td>
                    <td className="p-3">
                      <Badge variant={result.hasControl ? "default" : "outline"}>
                        {result.hasControl ? "Yes" : "No"}
                      </Badge>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>

      {/* Footer */}
      <div className="mt-8 text-center text-sm text-gray-500">
        <p>Generated by Reputation Tracker</p>
      </div>
    </div>
  );
}
